[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino

upload_port = COM3
upload_speed = 115200

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    SPI
lib_ldf_mode = deep+

